name: Update Language Stats

on:
  push:
    branches:
      - main

jobs:
  update-language-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Git configuration
      run: |
        git config --local user.name "GitHub Action"
        git config --local user.email "action@github.com"

    - name: Fetch Repositories and Language Stats
      run: |
        echo "Fetching repository list..."
        curl -s "https://api.github.com/users/${{ github.repository_owner }}/repos" \
          | jq -r '.[].languages_url' > urls.txt
        echo "Fetched URLs:"
        cat urls.txt

        echo "Fetching language stats..."
        xargs -n1 -I {} curl -s {} < urls.txt \
          | jq -s 'add' > languages.json

        echo "Language stats fetched:"
        cat languages.json

    - name: Commit and Push Changes
      run: |
        # Check if the files have changed
        if git diff --exit-code languages.json; then
          echo "No changes in language stats, skipping commit."
        else
          git add languages.json
          git commit -m "Update language stats"
          git push
        fi
